title: AM.SanGoCan
author: taiga
description: 缶ビールを片手に世間からはみ出てしまった二人がゆるゆるとトークします。
description_long: ゲームエンジニアのtaigaとSNSマーケターのhaseがパーソナリティを務めるキラキラバイブス全開の極貧アル中インターネットラジオ番組
hashtag: 350can
keywords: game,entertainment,local,news,market,art,anime
language: ja
markdown: kramdown
permalink: /episode/:title
timezone: Asia/Tokyo
url: https://350can.github.io
email: 2044taiga@gmail.com
actors:
  taiga:
    image_url: /images/actors/taiga.jpg
    name: taiga
    url: https://twitter.com/dn0t_
  hase:
    image_url: /images/actors/hase.jpg
    name: hase
    url: https://twitter.com/hase_csv
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
itunes_podcast_url:
sass:
  sass_dir: css
