title: RADIO 350CAN
author: taiga
description: それでも地球は回ってる。
description_long: どうしようもないふたりがどうしようもない話をする、先に誤っておくごめん。
hashtag: 350can
keywords: game,entertainment,local,news,market,art,anime
language: ja
markdown: kramdown
permalink: /episode/:title
timezone: Asia/Tokyo
url: https://350can.github.io
email: test@gmail.com
actors:
  taiga:
    image_url: /images/actors/taiga.jpg
    name: taiga
    url: https://twitter.com/dot_not_
  hase:
    image_url: /images/actors/hase.jpg
    name: hase
    url: https://twitter.com/hase_mp4
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
itunes_podcast_url:
sass:
  sass_dir: css
