title: AM.SanGoCan
author: taiga
description: エンジニアのtaigaとマーケターのhaseがパーソナリティを務めるキラキラバイブス全開の極貧アル中インターネットラジオ番組です。毎週更新！
description_long: 毎週木曜の深夜、缶ビールを片手に世間からはみ出てしまった二人がゆるゆると身近な事件から海の向こうのニュースまで様々な話題を持ち寄ってトークします。
hashtag: 350can
keywords: game,entertainment,local,news,market,art,anime
language: ja
markdown: kramdown
permalink: /episode/:title
timezone: Asia/Tokyo
url: https://350can.github.io
email: 2044taiga@gmail.com
actors:
  taiga:
    image_url: /images/actors/taiga.jpg
    name: taiga
    url: https://twitter.com/dn0t_
  hase:
    image_url: /images/actors/hase.jpg
    name: hase
    url: https://twitter.com/hase_csv
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
itunes_podcast_url:
sass:
  sass_dir: css
